"use client";
import { useState } from "react";

export default function SyncDealerDemo({ lang = "es" }) {
  const isEn = lang === "en";
  const [active, setActive] = useState("dashboard");

  const T = {
    brandLabel:  isEn ? "Almotores"              : "Almotores",
    activeBrands:isEn ? "Active brands"          : "Marcas activas",
    live:        isEn ? "● Live"                 : "● En vivo",
    month:       isEn ? "May 2025"               : "Mayo 2025",
    tabDash:     isEn ? "Dashboard"              : "Dashboard",
    tabPayroll:  isEn ? "Payroll PDF"            : "Nómina PDF",
    tabDeliv:    isEn ? "Deliveries"             : "Entregas",
    kpi1l:       isEn ? "Monthly sales"          : "Ventas del mes",
    kpi1s:       isEn ? "+12% vs last month"     : "+12% vs mes anterior",
    kpi2l:       isEn ? "Total commissions"      : "Comisiones totales",
    kpi2s:       isEn ? "COP — current payroll"  : "COP — nómina actual",
    kpi3l:       isEn ? "Bonuses generated"      : "Bonos generados",
    kpi3s:       isEn ? "advisors with bonus"    : "asesores con bono activo",
    colAdvisor:  isEn ? "Advisor"                : "Asesor",
    colBrand:    isEn ? "Brand"                  : "Marca",
    colSales:    isEn ? "Sales"                  : "Ventas",
    colComm:     isEn ? "Commission"             : "Comisión",
    colStatus:   isEn ? "Status"                 : "Estado",
    tagBonus:    isEn ? "✓ Bonus"                : "✓ Bono",
    tagBase:     isEn ? "Base"                   : "Base",
    payrollGen:  isEn ? "Payroll generator"      : "Generador de nómina",
    exportPDF:   isEn ? "↓ Export PDF"           : "↓ Exportar PDF",
    settlement:  isEn ? "Commission settlement — May 2025" : "Liquidación de comisiones — Mayo 2025",
    generatedBy: isEn ? "Generated by SyncDealer": "Generado por SyncDealer",
    totalComm:   isEn ? "Total commissions"      : "Total comisiones",
    traceLabel:  isEn ? "Vehicle traceability"   : "Trazabilidad de vehículos",
    stDelivered: isEn ? "Delivered"              : "Entregado",
    stProcess:   isEn ? "Processing"             : "En trámite",
    stReg:       isEn ? "Registered"             : "Matriculado",
    stPending:   isEn ? "Pending"                : "Pendiente",
    salesShort:  isEn ? "sales"                  : "vtas",
  };

  const screens = {
    dashboard: {
      label: T.tabDash, icon: "◈",
      content: () => (
        <div style={{ padding: "20px", display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 10 }}>
            {[
              { label: T.kpi1l, value: "47",    sub: T.kpi1s, color: "#6C63FF" },
              { label: T.kpi2l, value: "$18.4M", sub: T.kpi2s, color: "#00D4FF" },
              { label: T.kpi3l, value: "9",      sub: T.kpi3s, color: "#00ff88" },
            ].map((k, i) => (
              <div key={i} style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 8, padding: "14px 16px" }}>
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>{k.label}</div>
                <div style={{ fontFamily: "'Syne',sans-serif", fontSize: "1.6rem", fontWeight: 800, color: k.color, lineHeight: 1 }}>{k.value}</div>
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.3)", marginTop: 4 }}>{k.sub}</div>
              </div>
            ))}
          </div>
          <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, overflow: "hidden" }}>
            <div style={{ padding: "10px 14px", borderBottom: "1px solid rgba(255,255,255,0.05)", display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 80px", gap: 8 }}>
              {[T.colAdvisor, T.colBrand, T.colSales, T.colComm, T.colStatus].map(h => (
                <div key={h} style={{ fontSize: 9, color: "rgba(255,255,255,0.3)", textTransform: "uppercase", letterSpacing: "0.08em" }}>{h}</div>
              ))}
            </div>
            {[
              { name: "Carlos Mendez", marca: "KIA",     ventas: 8,  comision: "$2.4M", bonus: true },
              { name: "Laura Torres",  marca: "Renault",  ventas: 6,  comision: "$1.8M", bonus: false },
              { name: "Andrés Ríos",   marca: "VW",      ventas: 11, comision: "$3.3M", bonus: true },
              { name: "Milena Vargas", marca: "JAC",     ventas: 4,  comision: "$1.2M", bonus: false },
              { name: "Felipe Castro", marca: "KIA",     ventas: 9,  comision: "$2.7M", bonus: true },
            ].map((r, i) => (
              <div key={i} style={{ padding: "10px 14px", borderBottom: "1px solid rgba(255,255,255,0.04)", display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 80px", gap: 8, alignItems: "center" }}>
                <div style={{ fontSize: 11, color: "rgba(255,255,255,0.85)", fontWeight: 500 }}>{r.name}</div>
                <div style={{ fontSize: 10, color: "rgba(255,255,255,0.4)" }}>{r.marca}</div>
                <div style={{ fontSize: 11, color: "#00D4FF", fontWeight: 600 }}>{r.ventas}</div>
                <div style={{ fontSize: 11, color: "rgba(255,255,255,0.7)" }}>{r.comision}</div>
                <div style={{ fontSize: 9, padding: "2px 8px", borderRadius: 100, background: r.bonus ? "rgba(0,255,136,0.1)" : "rgba(108,99,255,0.1)", color: r.bonus ? "#00ff88" : "#6C63FF", border: `1px solid ${r.bonus ? "#00ff8830" : "#6C63FF30"}`, textAlign: "center" }}>
                  {r.bonus ? T.tagBonus : T.tagBase}
                </div>
              </div>
            ))}
          </div>
        </div>
      ),
    },
    nomina: {
      label: T.tabPayroll, icon: "◉",
      content: () => (
        <div style={{ padding: "20px", display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div>
              <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", textTransform: "uppercase", letterSpacing: "0.1em" }}>{T.payrollGen}</div>
              <div style={{ fontFamily: "'Syne',sans-serif", fontSize: "1.1rem", fontWeight: 700, color: "white" }}>{T.month}</div>
            </div>
            <button style={{ background: "linear-gradient(135deg,#6C63FF,#5a52e0)", border: "none", color: "white", padding: "8px 14px", borderRadius: 6, fontSize: 10, cursor: "pointer", letterSpacing: "0.08em" }}>{T.exportPDF}</button>
          </div>
          <div style={{ background: "white", borderRadius: 8, padding: "16px", color: "#111" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12, paddingBottom: 12, borderBottom: "2px solid #6C63FF" }}>
              <div>
                <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 13, fontWeight: 800, color: "#080810" }}>ALMOTORES S.A.</div>
                <div style={{ fontSize: 9, color: "#888", letterSpacing: "0.1em", textTransform: "uppercase" }}>{T.settlement}</div>
              </div>
              <div style={{ fontSize: 9, color: "#aaa" }}>{T.generatedBy}</div>
            </div>
            {[
              { name: "Carlos Mendez", ventas: 8,  comision: "$2.400.000", bono: "$400.000",  total: "$3.600.000" },
              { name: "Andrés Ríos",   ventas: 11, comision: "$3.300.000", bono: "$600.000",  total: "$4.700.000" },
              { name: "Felipe Castro", ventas: 9,  comision: "$2.700.000", bono: "$400.000",  total: "$3.900.000" },
            ].map((r, i) => (
              <div key={i} style={{ display: "grid", gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr", gap: 6, padding: "8px 0", borderBottom: "1px solid #f0f0f0", fontSize: 9, color: "#333" }}>
                <div style={{ fontWeight: 600 }}>{r.name}</div>
                <div style={{ textAlign: "center" }}>{r.ventas} {T.salesShort}</div>
                <div style={{ textAlign: "right" }}>{r.comision}</div>
                <div style={{ textAlign: "right", color: "#6C63FF" }}>{r.bono}</div>
                <div style={{ textAlign: "right", fontWeight: 700 }}>{r.total}</div>
              </div>
            ))}
            <div style={{ marginTop: 10, display: "flex", justifyContent: "flex-end", gap: 16 }}>
              <div style={{ fontSize: 9, color: "#888" }}>{T.totalComm}</div>
              <div style={{ fontSize: 12, fontWeight: 800, color: "#6C63FF" }}>$18.400.000 COP</div>
            </div>
          </div>
        </div>
      ),
    },
    entregas: {
      label: T.tabDeliv, icon: "◷",
      content: () => (
        <div style={{ padding: "20px", display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 4 }}>{T.traceLabel}</div>
          {[
            { placa: "ABC-123", modelo: "KIA Sportage 2024",   cliente: "Juan Hernández", asesor: "Carlos M.", estado: T.stDelivered, color: "#00ff88" },
            { placa: "XYZ-456", modelo: "Renault Duster 2025", cliente: "María López",    asesor: "Laura T.",  estado: T.stProcess,   color: "#ffb400" },
            { placa: "QRS-789", modelo: "VW Tiguan 2024",      cliente: "Roberto Silva",  asesor: "Andrés R.", estado: T.stReg,       color: "#00D4FF" },
            { placa: "DEF-321", modelo: "JAC JS4 2025",        cliente: "Claudia Mesa",   asesor: "Milena V.", estado: T.stPending,   color: "#ff6060" },
            { placa: "GHI-654", modelo: "KIA Stonic 2024",     cliente: "Pedro Arango",   asesor: "Felipe C.", estado: T.stDelivered, color: "#00ff88" },
          ].map((v, i) => (
            <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, padding: "12px 14px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{ width: 6, height: 6, borderRadius: "50%", background: v.color, flexShrink: 0 }} />
                <div>
                  <div style={{ fontSize: 11, color: "rgba(255,255,255,0.85)", fontWeight: 600 }}>{v.modelo}</div>
                  <div style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", marginTop: 2 }}>{v.placa} · {v.cliente} · {v.asesor}</div>
                </div>
              </div>
              <div style={{ textAlign: "right" }}>
                <div style={{ fontSize: 9, padding: "2px 8px", borderRadius: 100, background: `${v.color}15`, color: v.color, border: `1px solid ${v.color}30` }}>{v.estado}</div>
              </div>
            </div>
          ))}
        </div>
      ),
    },
  };

  const Screen = screens[active].content;

  return (
    <div style={{ background: "#0a0a14", borderRadius: 12, overflow: "hidden", border: "1px solid rgba(255,255,255,0.08)", fontFamily: "'DM Mono',monospace" }}>
      <div style={{ background: "#111120", padding: "10px 14px", display: "flex", alignItems: "center", gap: 8, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#ff5f57" }} />
        <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#febc2e" }} />
        <div style={{ width: 10, height: 10, borderRadius: "50%", background: "#28c840" }} />
        <div style={{ flex: 1, background: "rgba(255,255,255,0.05)", borderRadius: 6, padding: "4px 10px", fontSize: 9, color: "rgba(255,255,255,0.3)", marginLeft: 8 }}>syncdealear.almotores.com</div>
        <div style={{ fontSize: 9, color: "rgba(108,99,255,0.6)", letterSpacing: "0.1em" }}>SyncDealer v2</div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "180px 1fr", minHeight: 380 }}>
        <div style={{ background: "#080812", borderRight: "1px solid rgba(255,255,255,0.05)", padding: "16px 10px" }}>
          <div style={{ fontSize: 8, color: "rgba(255,255,255,0.25)", textTransform: "uppercase", letterSpacing: "0.15em", marginBottom: 12, paddingLeft: 6 }}>{T.brandLabel}</div>
          {Object.entries(screens).map(([key, s]) => (
            <button key={key} onClick={() => setActive(key)} style={{ width: "100%", display: "flex", alignItems: "center", gap: 8, padding: "9px 10px", borderRadius: 7, border: "none", background: active === key ? "rgba(108,99,255,0.15)" : "transparent", color: active === key ? "#6C63FF" : "rgba(255,255,255,0.35)", fontSize: 11, cursor: "pointer", marginBottom: 2, textAlign: "left", fontFamily: "'DM Mono',monospace", transition: "all 0.15s", borderLeft: active === key ? "2px solid #6C63FF" : "2px solid transparent" }}>
              <span style={{ fontSize: 13 }}>{s.icon}</span>{s.label}
            </button>
          ))}
          <div style={{ marginTop: 16, padding: "0 6px" }}>
            <div style={{ height: 1, background: "rgba(255,255,255,0.05)", marginBottom: 12 }} />
            <div style={{ fontSize: 9, color: "rgba(255,255,255,0.2)", marginBottom: 8 }}>{T.activeBrands}</div>
            {["KIA","Renault","VW","JAC"].map(m => (
              <div key={m} style={{ fontSize: 9, color: "rgba(255,255,255,0.3)", padding: "4px 0", display: "flex", alignItems: "center", gap: 6 }}>
                <div style={{ width: 4, height: 4, borderRadius: "50%", background: "rgba(108,99,255,0.5)" }} />{m}
              </div>
            ))}
          </div>
        </div>
        <div style={{ overflow: "auto", maxHeight: 420 }}>
          <div style={{ padding: "12px 20px", borderBottom: "1px solid rgba(255,255,255,0.05)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 13, fontWeight: 700, color: "white" }}>{screens[active].label}</div>
            <div style={{ display: "flex", gap: 8 }}>
              <div style={{ background: "rgba(0,212,255,0.1)", color: "#00D4FF", padding: "3px 10px", borderRadius: 100, fontSize: 9, border: "1px solid rgba(0,212,255,0.2)" }}>{T.month}</div>
              <div style={{ background: "rgba(0,255,136,0.1)", color: "#00ff88", padding: "3px 10px", borderRadius: 100, fontSize: 9, border: "1px solid rgba(0,255,136,0.2)" }}>{T.live}</div>
            </div>
          </div>
          <Screen />
        </div>
      </div>
    </div>
  );
}